services:
  db:
    image: postgres:16
    env_file:
      - .env.docker

    # хранилище для БД, чтобы БД каждый раз не пересоздавалась
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 3s
      timeout: 3s
      retries: 10
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    env_file:
      - .env.docker
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
